-- 2026-01-06: make username auth-friendly
-- Purpose: allow Supabase Auth to create auth.users rows without a username
-- (Auth only sends id and email). This migration:
--  - drops NOT NULL on username
--  - sets a safe autogenerated default for username
--  - backfills existing NULL usernames with unique defaults
--  - ensures a unique index exists for non-null usernames

-- Make username nullable and set a unique default based on uuid
ALTER TABLE public.users ALTER COLUMN username DROP NOT NULL;
ALTER TABLE public.users ALTER COLUMN username SET DEFAULT CONCAT('user_', LEFT(uuid_generate_v4()::text, 8));

-- Backfill any existing NULL usernames with generated unique values
UPDATE public.users
SET username = CONCAT('user_', LEFT(uuid_generate_v4()::text, 8))
WHERE username IS NULL;

-- Create a unique index for username values (non-null only)
-- This allows multiple NULLs but enforces uniqueness for present usernames.
CREATE UNIQUE INDEX IF NOT EXISTS users_username_key ON public.users (username) WHERE username IS NOT NULL;

-- NOTE: If you want to temporarily relax additional constraints for debugging,
-- you may (carefully) drop NOT NULL on email and/or drop unique indexes, then
-- re-add them after confirming signUp works. However, keep email NOT NULL in
-- production to preserve strong contact identification.
