-- =====================================================
-- ISKOMARKET SUPABASE DATABASE SCHEMA
-- Cavite State University Community Marketplace
-- Version: 1.0.0 (Production Ready)
-- Last Updated: December 13, 2025
-- =====================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Enable pgcrypto for password hashing
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =====================================================
-- USERS TABLE
-- Stores user profiles and authentication data
-- =====================================================
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email VARCHAR(255) UNIQUE NOT NULL,
  -- Make username nullable and provide a safe autogenerated default so Supabase Auth can insert users
  -- without sending a username (Auth only sends id and email by default).
  username VARCHAR(50) UNIQUE DEFAULT CONCAT('user_', LEFT(uuid_generate_v4()::text, 8)),
  program VARCHAR(255),
  college VARCHAR(255),
  -- removed: year_level, phone_number
  bio TEXT,
  avatar_url TEXT,
  
  -- Account status
  is_verified BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  is_suspended BOOLEAN DEFAULT FALSE,
  suspension_reason TEXT,
  suspension_until TIMESTAMP WITH TIME ZONE,
  is_admin BOOLEAN DEFAULT FALSE,
  
  -- Gamification
  iskoins INTEGER DEFAULT 50,
  locked_iskoins INTEGER DEFAULT 0,
  credit_score INTEGER DEFAULT 100 CHECK (credit_score >= 0 AND credit_score <= 100),
  rank_tier VARCHAR(20) DEFAULT 'Bronze',
  total_purchases INTEGER DEFAULT 0,
  total_sales INTEGER DEFAULT 0,
  successful_transactions INTEGER DEFAULT 0,
  
  -- Badges & Achievements
  is_top_buyer BOOLEAN DEFAULT FALSE,
  is_top_seller BOOLEAN DEFAULT FALSE,
  is_trusted_member BOOLEAN DEFAULT FALSE,
  badges JSONB DEFAULT '[]',
  
  -- Season & Rewards
  current_season INTEGER DEFAULT 1,
  season_points INTEGER DEFAULT 0,
  season_rank INTEGER,
  last_spin_date DATE,
  spin_count INTEGER DEFAULT 0,
  total_spins INTEGER DEFAULT 0,
  
  -- Customization (Premium)
  glow_effect VARCHAR(50),
  glow_expiry TIMESTAMP WITH TIME ZONE,
  
  -- Activity tracking
  last_active TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  inactivity_warning_sent BOOLEAN DEFAULT FALSE,
  inactivity_warning_date TIMESTAMP WITH TIME ZONE,
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- PRODUCTS TABLE
-- Stores marketplace product listings
-- =====================================================
CREATE TABLE products (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  seller_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  -- Product details
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  price DECIMAL(10, 2) NOT NULL CHECK (price >= 0),
  category VARCHAR(100) NOT NULL,
  condition VARCHAR(50) NOT NULL,
  
  -- Images (array of URLs)
  images JSONB DEFAULT '[]',
  
  -- Location & meetup
  location VARCHAR(255),
  meetup_locations JSONB DEFAULT '[]',
  
  -- Status
  is_available BOOLEAN DEFAULT TRUE,
  is_sold BOOLEAN DEFAULT FALSE,
  is_hidden BOOLEAN DEFAULT FALSE,
  is_deleted BOOLEAN DEFAULT FALSE,
  deletion_reason TEXT,
  
  -- For a Cause specific fields
  is_for_cause BOOLEAN DEFAULT FALSE,
  cause_organization VARCHAR(255),
  goal_amount DECIMAL(10, 2),
  raised_amount DECIMAL(10, 2) DEFAULT 0,
  
  -- Engagement metrics
  views INTEGER DEFAULT 0,
  interested INTEGER DEFAULT 0,
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  sold_at TIMESTAMP WITH TIME ZONE
);

-- =====================================================
-- TRANSACTIONS TABLE
-- Stores purchase transactions and order history
-- =====================================================
CREATE TABLE transactions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  
  -- Transaction parties
  buyer_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  seller_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  
  -- Transaction details
  amount DECIMAL(10, 2) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'pending', -- pending, confirmed, completed, cancelled, disputed
  
  -- Meetup details
  meetup_location VARCHAR(255),
  meetup_date TIMESTAMP WITH TIME ZONE,
  meetup_confirmed_by_buyer BOOLEAN DEFAULT FALSE,
  meetup_confirmed_by_seller BOOLEAN DEFAULT FALSE,
  
  -- Payment
  payment_method VARCHAR(50) DEFAULT 'cash', -- cash, gcash, etc
  payment_status VARCHAR(50) DEFAULT 'pending', -- pending, completed
  
  -- Completion & Ratings
  completed_at TIMESTAMP WITH TIME ZONE,
  buyer_rating INTEGER CHECK (buyer_rating >= 1 AND buyer_rating <= 5),
  buyer_review TEXT,
  seller_rating INTEGER CHECK (seller_rating >= 1 AND seller_rating <= 5),
  seller_review TEXT,
  
  -- Iskoin rewards
  iskoins_earned INTEGER DEFAULT 0,
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- CONVERSATIONS TABLE
-- Stores chat conversation threads (one per product per buyer-seller pair)
-- Core principle: ONE conversation per product per buyer-seller pair
-- =====================================================
CREATE TABLE conversations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  
  -- Conversation parties
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  buyer_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  seller_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  -- Last message tracking
  last_message_id UUID,
  last_message_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Ensure one conversation per product per buyer-seller pair
  UNIQUE(product_id, buyer_id, seller_id)
);

-- =====================================================
-- MESSAGES TABLE
-- Stores actual messages inside conversations
-- =====================================================
CREATE TABLE messages (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  
  -- Conversation reference
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  
  -- Message sender
  sender_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  -- Message content
  message_text TEXT NOT NULL,
  
  -- Message status
  is_read BOOLEAN DEFAULT FALSE,
  read_at TIMESTAMP WITH TIME ZONE,
  
  -- Auto-reply flag (for system-generated messages)
  is_auto_reply BOOLEAN DEFAULT FALSE,
  
  -- Automated message flags (for transaction-related messages)
  is_automated BOOLEAN DEFAULT FALSE,
  automation_type VARCHAR(50), -- meetup_request, meetup_confirmation, transaction_update, etc
  
  -- Related transaction (optional)
  transaction_id UUID REFERENCES transactions(id) ON DELETE SET NULL,
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- REVIEWS TABLE
-- Stores user reviews and ratings
-- =====================================================
CREATE TABLE reviews (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  
  -- Review parties
  reviewer_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reviewed_user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  -- Related transaction
  transaction_id UUID REFERENCES transactions(id) ON DELETE CASCADE,
  product_id UUID REFERENCES products(id) ON DELETE CASCADE,
  
  -- Review content
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  
  -- Review status
  is_visible BOOLEAN DEFAULT TRUE,
  is_flagged BOOLEAN DEFAULT FALSE,
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- REPORTS TABLE
-- Stores user reports for moderation
-- =====================================================
CREATE TABLE reports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  
  -- Reporter
  reporter_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  -- Reported entity
  reported_type VARCHAR(50) NOT NULL, -- user, product, message, review
  reported_id UUID NOT NULL,
  reported_user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  
  -- Report details
  reason VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  evidence_urls JSONB DEFAULT '[]',
  
  -- Status
  status VARCHAR(50) DEFAULT 'pending', -- pending, reviewing, resolved, dismissed
  admin_notes TEXT,
  resolved_by UUID REFERENCES users(id) ON DELETE SET NULL,
  resolved_at TIMESTAMP WITH TIME ZONE,
  
  -- Actions taken
  action_taken VARCHAR(100), -- warning, suspension, deletion, none
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- NOTIFICATIONS TABLE
-- Stores user notifications
-- =====================================================
CREATE TABLE notifications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  
  -- Notification recipient
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  -- Notification content
  type VARCHAR(50) NOT NULL, -- message, transaction, review, report, system, achievement
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  
  -- Related entities
  related_id UUID,
  related_type VARCHAR(50), -- product, transaction, message, user
  
  -- Action URL (optional)
  action_url TEXT,
  
  -- Status
  is_read BOOLEAN DEFAULT FALSE,
  read_at TIMESTAMP WITH TIME ZONE,
  
  -- Priority
  priority VARCHAR(20) DEFAULT 'normal', -- low, normal, high, urgent
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- ANNOUNCEMENTS TABLE
-- Stores platform announcements
-- =====================================================
CREATE TABLE announcements (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  
  -- Announcement content
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  type VARCHAR(50) NOT NULL DEFAULT 'info', -- info, warning, success, error, update
  
  -- Targeting
  target_audience VARCHAR(50) DEFAULT 'all', -- all, students, admins, specific_college
  target_colleges JSONB DEFAULT '[]',
  
  -- Display settings
  is_active BOOLEAN DEFAULT TRUE,
  is_banner BOOLEAN DEFAULT FALSE,
  is_popup BOOLEAN DEFAULT FALSE,
  priority INTEGER DEFAULT 0,
  
  -- Display duration
  start_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  end_date TIMESTAMP WITH TIME ZONE,
  
  -- Action button (optional)
  action_label VARCHAR(100),
  action_url TEXT,
  
  -- Created by
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- ANNOUNCEMENT_VIEWS TABLE
-- Tracks which users have seen announcements
-- =====================================================
CREATE TABLE announcement_views (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  announcement_id UUID NOT NULL REFERENCES announcements(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  viewed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(announcement_id, user_id)
);

-- =====================================================
-- SEASONS TABLE
-- Stores season/competition periods
-- =====================================================
CREATE TABLE seasons (
  id SERIAL PRIMARY KEY,
  season_number INTEGER UNIQUE NOT NULL,
  name VARCHAR(100) NOT NULL,
  
  -- Duration
  start_date TIMESTAMP WITH TIME ZONE NOT NULL,
  end_date TIMESTAMP WITH TIME ZONE NOT NULL,
  
  -- Status
  is_active BOOLEAN DEFAULT FALSE,
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- SEASON_LEADERBOARD REMOVED: table and schema dropped by migration
-- See migrations/20251220-drop-season-leaderboard.sql for details


-- =====================================================
-- ISKOIN_TRANSACTIONS TABLE
-- Stores Iskoin earning and spending history
-- =====================================================
CREATE TABLE iskoin_transactions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  -- Transaction details
  amount INTEGER NOT NULL, -- positive for earned, negative for spent
  type VARCHAR(50) NOT NULL, -- earned, spent, bonus, spin, redeem, season_lock, season_unlock
  description TEXT NOT NULL,
  
  -- Related entity
  related_id UUID,
  related_type VARCHAR(50), -- transaction, spin, reward, season
  
  -- Balance snapshot
  balance_before INTEGER NOT NULL,
  balance_after INTEGER NOT NULL,
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- DAILY_SPINS TABLE
-- Stores daily spin results
-- =====================================================
CREATE TABLE daily_spins (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  -- Spin result
  reward_type VARCHAR(50) NOT NULL, -- iskoins, discount, badge, nothing
  reward_amount INTEGER DEFAULT 0,
  reward_description TEXT,
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- CREDIT_SCORE_HISTORY TABLE
-- Stores credit score change history
-- =====================================================
CREATE TABLE credit_score_history (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  -- Score change
  change_amount INTEGER NOT NULL, -- positive or negative
  reason VARCHAR(255) NOT NULL,
  
  -- Score snapshot
  score_before INTEGER NOT NULL,
  score_after INTEGER NOT NULL,
  
  -- Related entity
  related_id UUID,
  related_type VARCHAR(50), -- transaction, report, suspension
  
  -- Performed by (for admin actions)
  performed_by UUID REFERENCES users(id) ON DELETE SET NULL,
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- MODERATION_LOGS TABLE
-- Stores admin moderation actions
-- =====================================================
CREATE TABLE moderation_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  
  -- Admin who performed action
  admin_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  -- Action details
  action_type VARCHAR(50) NOT NULL, -- suspend_user, delete_product, resolve_report, etc
  target_type VARCHAR(50) NOT NULL, -- user, product, report, message
  target_id UUID NOT NULL,
  
  -- Action details
  reason TEXT NOT NULL,
  notes TEXT,
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- OTP_VERIFICATIONS TABLE
-- Stores OTP codes for email verification
-- =====================================================
CREATE TABLE otp_verifications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  
  -- User details
  email VARCHAR(255) NOT NULL,
  otp_code VARCHAR(6) NOT NULL,
  
  -- OTP status
  is_used BOOLEAN DEFAULT FALSE,
  is_expired BOOLEAN DEFAULT FALSE,
  attempts INTEGER DEFAULT 0,
  
  -- Expiry
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  
  -- Purpose
  purpose VARCHAR(50) NOT NULL, -- registration, password_reset, email_change
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- SYSTEM_SETTINGS TABLE
-- Stores platform configuration
-- =====================================================
CREATE TABLE system_settings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  key VARCHAR(100) UNIQUE NOT NULL,
  value JSONB NOT NULL,
  description TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- INDEXES for Performance Optimization
-- =====================================================

-- Users indexes
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_username ON users(username);
-- removed: CREATE INDEX idx_users_student_number (student_number removed)
CREATE INDEX idx_users_is_active ON users(is_active);
CREATE INDEX idx_users_created_at ON users(created_at);

-- Products indexes
CREATE INDEX idx_products_seller_id ON products(seller_id);
CREATE INDEX idx_products_category ON products(category);
CREATE INDEX idx_products_is_available ON products(is_available);
CREATE INDEX idx_products_is_sold ON products(is_sold);
CREATE INDEX idx_products_created_at ON products(created_at DESC);
CREATE INDEX idx_products_price ON products(price);

-- Transactions indexes
CREATE INDEX idx_transactions_buyer_id ON transactions(buyer_id);
CREATE INDEX idx_transactions_seller_id ON transactions(seller_id);
CREATE INDEX idx_transactions_product_id ON transactions(product_id);
CREATE INDEX idx_transactions_status ON transactions(status);
CREATE INDEX idx_transactions_created_at ON transactions(created_at DESC);

-- Conversations indexes
CREATE INDEX idx_conversations_product_id ON conversations(product_id);
CREATE INDEX idx_conversations_buyer_id ON conversations(buyer_id);
CREATE INDEX idx_conversations_seller_id ON conversations(seller_id);
CREATE INDEX idx_conversations_last_message_at ON conversations(last_message_at DESC);

-- Messages indexes
CREATE INDEX idx_messages_conversation_id ON messages(conversation_id);
CREATE INDEX idx_messages_sender_id ON messages(sender_id);
CREATE INDEX idx_messages_created_at ON messages(created_at DESC);
CREATE INDEX idx_messages_is_read ON messages(is_read);

-- Reviews indexes
CREATE INDEX idx_reviews_reviewed_user_id ON reviews(reviewed_user_id);
CREATE INDEX idx_reviews_reviewer_id ON reviews(reviewer_id);
CREATE INDEX idx_reviews_transaction_id ON reviews(transaction_id);

-- Reports indexes
CREATE INDEX idx_reports_reporter_id ON reports(reporter_id);
CREATE INDEX idx_reports_reported_user_id ON reports(reported_user_id);
CREATE INDEX idx_reports_status ON reports(status);
CREATE INDEX idx_reports_created_at ON reports(created_at DESC);

-- Notifications indexes
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_is_read ON notifications(is_read);
CREATE INDEX idx_notifications_created_at ON notifications(created_at DESC);

-- Announcements indexes
CREATE INDEX idx_announcements_is_active ON announcements(is_active);
CREATE INDEX idx_announcements_start_date ON announcements(start_date);
CREATE INDEX idx_announcements_end_date ON announcements(end_date);

-- Iskoin transactions indexes
CREATE INDEX idx_iskoin_transactions_user_id ON iskoin_transactions(user_id);
CREATE INDEX idx_iskoin_transactions_created_at ON iskoin_transactions(created_at DESC);

-- Daily spins indexes
CREATE INDEX idx_daily_spins_user_id ON daily_spins(user_id);
CREATE INDEX idx_daily_spins_created_at ON daily_spins(created_at DESC);

-- Credit score history indexes
CREATE INDEX idx_credit_score_history_user_id ON credit_score_history(user_id);
CREATE INDEX idx_credit_score_history_created_at ON credit_score_history(created_at DESC);

-- OTP verifications indexes
CREATE INDEX idx_otp_email ON otp_verifications(email);
CREATE INDEX idx_otp_expires_at ON otp_verifications(expires_at);
CREATE INDEX idx_otp_is_used ON otp_verifications(is_used);

-- =====================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =====================================================

-- Enable RLS on all tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE announcement_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE seasons ENABLE ROW LEVEL SECURITY;
-- season_leaderboard RLS removed (table dropped via migration).
ALTER TABLE iskoin_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_spins ENABLE ROW LEVEL SECURITY;
ALTER TABLE credit_score_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE moderation_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE otp_verifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;

-- Users policies
CREATE POLICY "Users can view all active users"
  ON users FOR SELECT
  USING (is_active = true);

CREATE POLICY "Users can update own profile"
  ON users FOR UPDATE
  USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
  ON users FOR INSERT
  WITH CHECK (auth.uid() = id);

-- Products policies
CREATE POLICY "Anyone can view available products"
  ON products FOR SELECT
  USING (is_available = true AND is_deleted = false);

CREATE POLICY "Users can create products"
  ON products FOR INSERT
  WITH CHECK (auth.uid() = seller_id);

CREATE POLICY "Users can update own products"
  ON products FOR UPDATE
  USING (auth.uid() = seller_id);

-- Transactions policies
CREATE POLICY "Users can view own transactions"
  ON transactions FOR SELECT
  USING (auth.uid() = buyer_id OR auth.uid() = seller_id);

CREATE POLICY "Buyers can create transactions"
  ON transactions FOR INSERT
  WITH CHECK (auth.uid() = buyer_id);

CREATE POLICY "Transaction parties can update"
  ON transactions FOR UPDATE
  USING (auth.uid() = buyer_id OR auth.uid() = seller_id);

-- Conversations policies
CREATE POLICY "Users can view own conversations"
  ON conversations FOR SELECT
  USING (auth.uid() = buyer_id OR auth.uid() = seller_id);

CREATE POLICY "Buyers can create conversations"
  ON conversations FOR INSERT
  WITH CHECK (auth.uid() = buyer_id);

CREATE POLICY "Conversation parties can update"
  ON conversations FOR UPDATE
  USING (auth.uid() = buyer_id OR auth.uid() = seller_id);

-- Messages policies
CREATE POLICY "Users can view messages in their conversations"
  ON messages FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM conversations 
    WHERE conversations.id = messages.conversation_id 
    AND (conversations.buyer_id = auth.uid() OR conversations.seller_id = auth.uid())
  ));

CREATE POLICY "Users can send messages in their conversations"
  ON messages FOR INSERT
  WITH CHECK (
    auth.uid() = sender_id 
    AND EXISTS (
      SELECT 1 FROM conversations 
      WHERE conversations.id = conversation_id 
      AND (conversations.buyer_id = auth.uid() OR conversations.seller_id = auth.uid())
    )
  );

CREATE POLICY "Users can mark messages as read"
  ON messages FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM conversations 
    WHERE conversations.id = messages.conversation_id 
    AND (conversations.buyer_id = auth.uid() OR conversations.seller_id = auth.uid())
  ));

-- Reviews policies
CREATE POLICY "Anyone can view reviews"
  ON reviews FOR SELECT
  USING (is_visible = true);

CREATE POLICY "Users can create reviews"
  ON reviews FOR INSERT
  WITH CHECK (auth.uid() = reviewer_id);

-- Reports policies
CREATE POLICY "Users can view own reports"
  ON reports FOR SELECT
  USING (auth.uid() = reporter_id);

CREATE POLICY "Users can create reports"
  ON reports FOR INSERT
  WITH CHECK (auth.uid() = reporter_id);

-- Notifications policies
CREATE POLICY "Users can view own notifications"
  ON notifications FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can update own notifications"
  ON notifications FOR UPDATE
  USING (auth.uid() = user_id);

-- Announcements policies
CREATE POLICY "Anyone can view active announcements"
  ON announcements FOR SELECT
  USING (is_active = true AND NOW() >= start_date AND (end_date IS NULL OR NOW() <= end_date));

-- Announcement views policies
CREATE POLICY "Users can create own announcement views"
  ON announcement_views FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view own announcement views"
  ON announcement_views FOR SELECT
  USING (auth.uid() = user_id);

-- Seasons policies
CREATE POLICY "Anyone can view seasons"
  ON seasons FOR SELECT
  USING (true);

-- Season leaderboard policies
-- season_leaderboard policy removed by migration.

-- Iskoin transactions policies
CREATE POLICY "Users can view own iskoin transactions"
  ON iskoin_transactions FOR SELECT
  USING (auth.uid() = user_id);

-- Daily spins policies
CREATE POLICY "Users can view own spins"
  ON daily_spins FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own spins"
  ON daily_spins FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Credit score history policies
CREATE POLICY "Users can view own credit history"
  ON credit_score_history FOR SELECT
  USING (auth.uid() = user_id);

-- Admin policies (for moderation_logs and system_settings)
CREATE POLICY "Admins can view moderation logs"
  ON moderation_logs FOR SELECT
  USING (EXISTS (SELECT 1 FROM users WHERE id = auth.uid() AND is_admin = true));

CREATE POLICY "Admins can create moderation logs"
  ON moderation_logs FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM users WHERE id = auth.uid() AND is_admin = true));

CREATE POLICY "Admins can view system settings"
  ON system_settings FOR SELECT
  USING (EXISTS (SELECT 1 FROM users WHERE id = auth.uid() AND is_admin = true));

CREATE POLICY "Admins can update system settings"
  ON system_settings FOR UPDATE
  USING (EXISTS (SELECT 1 FROM users WHERE id = auth.uid() AND is_admin = true));

-- OTP verifications policies (system use only)
CREATE POLICY "System can manage OTP"
  ON otp_verifications FOR ALL
  USING (true);

-- =====================================================
-- FUNCTIONS & TRIGGERS
-- =====================================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at trigger to tables
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON products
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_transactions_updated_at BEFORE UPDATE ON transactions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_reports_updated_at BEFORE UPDATE ON reports
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_announcements_updated_at BEFORE UPDATE ON announcements
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Function to calculate user credit score
CREATE OR REPLACE FUNCTION calculate_credit_score(user_uuid UUID)
RETURNS INTEGER AS $$
DECLARE
  base_score INTEGER := 100;
  completed_trans INTEGER;
  positive_reviews INTEGER;
  negative_reviews INTEGER;
  reports_against INTEGER;
  final_score INTEGER;
BEGIN
  -- Get completed transactions
  SELECT COUNT(*) INTO completed_trans
  FROM transactions
  WHERE (buyer_id = user_uuid OR seller_id = user_uuid)
  AND status = 'completed';
  
  -- Get positive reviews (4-5 stars)
  SELECT COUNT(*) INTO positive_reviews
  FROM reviews
  WHERE reviewed_user_id = user_uuid AND rating >= 4;
  
  -- Get negative reviews (1-2 stars)
  SELECT COUNT(*) INTO negative_reviews
  FROM reviews
  WHERE reviewed_user_id = user_uuid AND rating <= 2;
  
  -- Get reports against user
  SELECT COUNT(*) INTO reports_against
  FROM reports
  WHERE reported_user_id = user_uuid AND status = 'resolved';
  
  -- Calculate score
  final_score := base_score 
    + (completed_trans * 2)
    + (positive_reviews * 3)
    - (negative_reviews * 5)
    - (reports_against * 10);
  
  -- Ensure score is between 0 and 100
  IF final_score > 100 THEN final_score := 100; END IF;
  IF final_score < 0 THEN final_score := 0; END IF;
  
  RETURN final_score;
END;
$$ LANGUAGE plpgsql;

-- Function to clean expired OTPs
CREATE OR REPLACE FUNCTION clean_expired_otps()
RETURNS void AS $$
BEGIN
  UPDATE otp_verifications
  SET is_expired = true
  WHERE expires_at < NOW() AND is_expired = false;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- INITIAL DATA
-- =====================================================

-- Insert default system settings
INSERT INTO system_settings (key, value, description) VALUES
  ('platform_name', '"IskoMarket"', 'Platform name'),
  ('maintenance_mode', 'false', 'Enable/disable maintenance mode'),
  ('registration_enabled', 'true', 'Enable/disable new user registration'),
  ('min_iskoin_transaction', '5', 'Minimum Iskoin amount for transactions'),
  ('daily_spin_enabled', 'true', 'Enable/disable daily spin feature'),
  ('season_enabled', 'true', 'Enable/disable season competition'),
  ('max_products_per_user', '50', 'Maximum products a user can list'),
  ('inactivity_days_warning', '60', 'Days of inactivity before warning'),
  ('inactivity_days_suspension', '90', 'Days of inactivity before suspension');

-- Insert first season
INSERT INTO seasons (season_number, name, start_date, end_date, is_active) VALUES
  (1, 'Inaugural Season', NOW(), NOW() + INTERVAL '90 days', true);

-- Insert default meetup locations
INSERT INTO system_settings (key, value, description) VALUES
  ('meetup_locations', '["Main Gate", "CvSU Library", "CvSU Cafeteria", "Engineering Building", "Admin Building", "Gymnasium", "Student Center", "Campus Park"]', 'Available meetup locations');

-- Insert default product categories
INSERT INTO system_settings (key, value, description) VALUES
  ('product_categories', '["Electronics", "Books & School Supplies", "Clothing & Accessories", "Home & Living", "Sports & Hobbies", "Services", "For a Cause", "Others"]', 'Product categories');

-- =====================================================
-- VIEWS for Easy Querying
-- =====================================================

-- View: Active products with seller info
CREATE OR REPLACE VIEW active_products_view AS
SELECT 
  p.*,
  u.username as seller_username,
  u.username as seller_name,
  u.avatar_url as seller_avatar,
  u.credit_score as seller_credit_score,
  u.is_trusted_member as seller_is_trusted
FROM products p
LEFT JOIN users u ON p.seller_id = u.id
WHERE (p.is_available IS NULL OR p.is_available = true)
  AND COALESCE(p.is_deleted, false) = false
  AND COALESCE(p.is_hidden, false) = false
  AND COALESCE(u.is_active, true) = true
  AND COALESCE(u.is_suspended, false) = false;

-- View: User statistics
CREATE OR REPLACE VIEW user_stats_view AS
SELECT 
  u.id,
  u.username,
  u.username as full_name,
  u.credit_score,
  u.iskoins,
  u.total_purchases,
  u.total_sales,
  COUNT(DISTINCT t.id) as completed_transactions,
  COALESCE(AVG(r.rating), 0) as average_rating,
  COUNT(DISTINCT r.id) as total_reviews
FROM users u
LEFT JOIN transactions t ON (u.id = t.buyer_id OR u.id = t.seller_id) AND t.status = 'completed'
LEFT JOIN reviews r ON u.id = r.reviewed_user_id
GROUP BY u.id;

-- =====================================================
-- STORAGE BUCKETS (Run these in Supabase Dashboard)
-- =====================================================

-- Create storage buckets for file uploads:
-- 1. Go to Supabase Dashboard > Storage
-- 2. Create the following buckets:
--    - avatars (public)
--    - product-images (public)
--    - report-evidence (private)

-- Storage policies will be configured in the dashboard

-- =====================================================
-- COMPLETE! 
-- =====================================================
-- This schema is now ready for production use.
-- Next steps:
-- 1. Copy this entire SQL script to Supabase SQL Editor
-- 2. Execute the script
-- 3. Create storage buckets in Supabase Dashboard
-- 4. Configure email templates for OTP in Supabase Auth settings
-- 5. Set up custom SMTP for @cvsu.edu.ph emails
-- 6. Update environment variables in your application
-- =====================================================